URLShortener/Controllers/DescriptionController.cs
using Microsoft.AspNetCore.Mvc;
using UrlShortener.Models;

namespace URLShortener.Controllers
{
    public class DescriptionController : Controller
    {
        static string fileName = "Description.txt";
        static string filePath = Path.Combine(Environment.CurrentDirectory, fileName);


        private DescriptionModel? _description;

        public DescriptionController()
        {
            _description = DescriptionModel.LoadFromFile(filePath);
        }

        public DescriptionModel Description { get; set; }

        public IActionResult Index()
        {
            return View(_description);
        }


        public IActionResult Edit()
        {
            return View(_description);
        }

        [HttpPost]
        public IActionResult Edit(DescriptionModel newText)
        {


            if (newText != null)
            {
                _description = newText;

                _description.SaveToFile(filePath);
                TempData["success"] = "Description updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

URLShortener/Controllers/URLItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using shortid;
using shortid.Configuration;
using URLShortener.DataAccess.Repository.IRepository;
using URLShortener.Models;
using URLShortener.Utility;


namespace URLShortener.Controllers
{

    public class URLItemController : Controller

    {
        UserManager<IdentityUser> UserManager;

        private readonly IUnitOfWork _unitOfWork;
        private const string ServiceUrl = "http://localhost:7254";
        public URLItemController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            UserManager = userManager;
        }

        public IActionResult Index()
        {
            List<UrlItem> UrlItems = _unitOfWork.UrlItem.GetAll().ToList();
            return View(UrlItems);
        }

        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_USER)]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_USER)]
        [HttpPost]
        public IActionResult Create(UrlItem obj)
        {
            if (obj.Url != null && obj.Url.Length < 9)
            {
                ModelState.AddModelError("url", "The url is wrong");
            }
            else if (obj.Url?.Substring(0, 8) != "https://")
            {
                ModelState.AddModelError("url", "The url is wrong");
            }


            string? longUrl = obj.Url;
            var shortenedUrlCollection = _unitOfWork.UrlItem.GetAll();
            var shortenedUrl = shortenedUrlCollection.FirstOrDefault(x => x.Url == longUrl);
            if (shortenedUrl == null)
            {
                var shortCode = ShortId.Generate(new GenerationOptions(length: 9));

                obj.ShortedUrl = $"{ServiceUrl}/{shortCode}";

                obj.ShortCode = shortCode;

                obj.CreatedBy = UserManager.GetUserName(User);
            }
            else
            {
                ModelState.AddModelError("url", "The url is already Exist");
            }



            if (ModelState.IsValid)
            {

                _unitOfWork.UrlItem.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "URL is added successfully";
                return RedirectToAction("Index");
            }


            return View();
        }

        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_USER)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var url = _unitOfWork.UrlItem.Get(item => item.Id == id);
            if (url == null)
            {
                return NotFound();
            }

            if (url.CreatedBy == UserManager.GetUserName(User))
            {
                _unitOfWork.UrlItem.Remove(url);
                _unitOfWork.Save();
                TempData["success"] = "URL is deleted successfully";

            }




            return RedirectToAction("Index");
        }
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_USER)]
        public IActionResult Details(int? id)
        {
            UrlItem UrlItems = _unitOfWork.UrlItem.Get(item => item.Id == id);
            return View(UrlItems);
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult DeleteAll()
        {

            List<UrlItem> UrlItems = _unitOfWork.UrlItem.GetAll().ToList();

            foreach (var urlItem in UrlItems)
            {
                _unitOfWork.UrlItem.Remove(urlItem);
            }
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

URLShortener/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - URLShortener</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/URLShortener.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="URLItem" asp-action="Index">URLShortener</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="URLItem" asp-action="Index">UrlsTable</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Description" asp-action="Index">Description about script</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications"/>
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer bg-primary text-muted ">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Bohdan
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/yl6azwbmp0yzi2nzqpkvlcfshays7bvp744rz10x89zfz1ws/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

URLShortener/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">toastr.success('@TempData["success"]');</script>
    
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.error('@TempData["error"]');</script>
}